version: '3.7'

services:
    backend:
      build: ../../set1/1-12/backend-example-docker/
      container_name: backend
      ports:
        - "8000:8000"
    frontend:
      build: ../../set1/1-12/frontend-example-docker/
      container_name: frontend
      ports:
        - "5000:5000"


