version: '3.7'

#the site responds at http://localhost:3000
services:

    proxy:
      image: jwilder/nginx-proxy
      volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
      ports:
        - 3000:3000
      depends_on:
        - frontend
      networks:
        - site-network

    frontend:
      build: ../../set1/1-12/frontend-example-docker/
      container_name: frontend
      ports:
        - "5000:5000"
      depends_on:
        - backend
      networks:
        - site-network

    backend:
      build: ../../set1/1-12/backend-example-docker/
      container_name: backend
      ports:
        - "8000:8000"
      networks:
        - site-network
      environment:
        - REDIS=redis
        - DB_USERNAME=postgres
        - DB_HOST=postgres
        - DB_PASSWORD=postgres-password
      depends_on:
        - redis
        - postgres

    redis:
      image: redis
      networks:
        - site-network

    postgres:
      image: postgres
      restart: unless-stopped
      environment:
        - POSTGRES_USER=postgres
        - POSTGES_PASSWORD=postgres-password
      container_name: postgres
      volumes:
        - pgdata:/var/lib/postgresql/data
      networks:
        - site-network
      ports:
        - "5432:5432"

networks:
  site-network:
    name: site-network
volumes:
  pgdata:
  files: